language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - pip install python-coveralls

# command to run tests
script:  py.test --cov abito --cov-report term-missing tests

after_success:
  - coveralls
